// Copyright (c) 2026 Naresh. All rights reserved.
// Licensed under the MIT License. See LICENSE file for details.

// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod commands;
mod sidecar;

use commands::agent::AgentState;

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_notification::init())
        .manage(AgentState::new())
        .invoke_handler(tauri::generate_handler![
            // Auth commands
            commands::auth::get_provider_api_key,
            commands::auth::set_provider_api_key,
            commands::auth::delete_provider_api_key,
            commands::auth::get_google_api_key,
            commands::auth::set_google_api_key,
            commands::auth::delete_google_api_key,
            commands::auth::get_openai_api_key,
            commands::auth::set_openai_api_key,
            commands::auth::delete_openai_api_key,
            commands::auth::get_fal_api_key,
            commands::auth::set_fal_api_key,
            commands::auth::delete_fal_api_key,
            commands::auth::get_exa_api_key,
            commands::auth::set_exa_api_key,
            commands::auth::delete_exa_api_key,
            commands::auth::get_tavily_api_key,
            commands::auth::set_tavily_api_key,
            commands::auth::delete_tavily_api_key,
            commands::auth::validate_provider_connection,
            commands::auth::fetch_provider_models,
            commands::auth::get_api_key,
            commands::auth::set_api_key,
            commands::auth::delete_api_key,
            commands::auth::get_stitch_api_key,
            commands::auth::set_stitch_api_key,
            commands::auth::delete_stitch_api_key,
            commands::auth::auth_logout_and_cleanup,
            commands::auth::auth_get_security_posture,
            commands::auth::validate_api_key,
            commands::auth::fetch_models,
            // File commands
            commands::files::read_file,
            commands::files::write_file,
            commands::files::list_directory,
            commands::files::open_file_preview,
            // Agent commands
            commands::agent::agent_set_api_key,
            commands::agent::agent_set_runtime_config,
            commands::agent::agent_get_capability_snapshot,
            commands::agent::agent_get_external_cli_availability,
            commands::agent::agent_set_stitch_api_key,
            commands::agent::agent_create_session,
            commands::agent::agent_send_message,
            commands::agent::agent_send_message_v2,
            commands::agent::agent_resume_run,
            commands::agent::agent_branch_session,
            commands::agent::agent_merge_branch,
            commands::agent::agent_set_active_branch,
            commands::agent::agent_get_run_timeline,
            commands::agent::agent_run_benchmark,
            commands::agent::agent_get_release_gate_status,
            commands::agent::agent_assert_release_gate,
            commands::agent::agent_respond_permission,
            commands::agent::agent_set_approval_mode,
            commands::agent::agent_set_execution_mode,
            commands::agent::agent_set_models,
            commands::agent::agent_respond_question,
            commands::agent::agent_stop_generation,
            commands::agent::agent_get_queue,
            commands::agent::agent_remove_from_queue,
            commands::agent::agent_reorder_queue,
            commands::agent::agent_send_queued_immediately,
            commands::agent::agent_edit_queued_message,
            commands::agent::agent_list_sessions,
            commands::agent::agent_list_sessions_page,
            commands::agent::agent_get_session,
            commands::agent::agent_get_session_chunk,
            commands::agent::agent_get_bootstrap_state,
            commands::agent::agent_get_events_since,
            commands::agent::agent_subscribe_events,
            commands::agent::agent_delete_session,
            commands::agent::agent_update_session_title,
            commands::agent::agent_update_session_working_directory,
            commands::agent::agent_update_session_last_accessed,
            commands::agent::agent_load_memory,
            commands::agent::agent_save_memory,
            commands::agent::agent_get_context_usage,
            commands::agent::agent_set_mcp_servers,
            commands::agent::agent_set_skills,
            commands::agent::agent_set_specialized_models,
            commands::agent::agent_mcp_call_tool,
            commands::agent::agent_load_gemini_extensions,
            commands::agent::agent_get_initialization_status,
            commands::agent::agent_command,
            commands::agent::agent_log_client_diagnostic,
            // Skill commands
            commands::skills::agent_discover_skills,
            commands::skills::agent_install_skill,
            commands::skills::agent_uninstall_skill,
            commands::skills::agent_check_skill_eligibility,
            commands::skills::agent_get_skill_content,
            commands::skills::agent_create_skill,
            commands::skills::agent_draft_skill_from_session,
            commands::skills::agent_create_skill_from_session,
            commands::skills::agent_ensure_default_skill_creator_installed,
            // Cron commands
            commands::cron::cron_list_jobs,
            commands::cron::cron_get_job,
            commands::cron::cron_create_job,
            commands::cron::cron_update_job,
            commands::cron::cron_delete_job,
            commands::cron::cron_pause_job,
            commands::cron::cron_resume_job,
            commands::cron::cron_trigger_job,
            commands::cron::cron_get_runs,
            commands::cron::cron_get_status,
            // Workflow commands
            commands::workflow::workflow_list,
            commands::workflow::workflow_get,
            commands::workflow::workflow_create_draft,
            commands::workflow::workflow_create_from_prompt,
            commands::workflow::workflow_update_draft,
            commands::workflow::workflow_validate,
            commands::workflow::workflow_publish,
            commands::workflow::workflow_archive,
            commands::workflow::workflow_run,
            commands::workflow::workflow_list_runs,
            commands::workflow::workflow_get_run,
            commands::workflow::workflow_get_run_events,
            commands::workflow::workflow_cancel_run,
            commands::workflow::workflow_pause_run,
            commands::workflow::workflow_resume_run,
            commands::workflow::workflow_backfill_schedule,
            commands::workflow::workflow_list_scheduled,
            commands::workflow::workflow_pause_scheduled,
            commands::workflow::workflow_resume_scheduled,
            commands::workflow::workflow_evaluate_triggers,
            // Heartbeat commands
            commands::heartbeat::heartbeat_get_status,
            commands::heartbeat::heartbeat_get_config,
            commands::heartbeat::heartbeat_set_config,
            commands::heartbeat::heartbeat_start,
            commands::heartbeat::heartbeat_stop,
            commands::heartbeat::heartbeat_wake,
            commands::heartbeat::heartbeat_queue_event,
            commands::heartbeat::heartbeat_get_events,
            commands::heartbeat::heartbeat_clear_events,
            // Policy commands
            commands::policy::policy_get,
            commands::policy::policy_update,
            commands::policy::policy_set_profile,
            commands::policy::policy_add_rule,
            commands::policy::policy_remove_rule,
            commands::policy::policy_evaluate,
            commands::policy::policy_reset,
            commands::policy::policy_get_profiles,
            commands::policy::policy_get_groups,
            // Deep Agents memory commands
            commands::deep::deep_memory_init,
            commands::deep::deep_memory_list,
            commands::deep::deep_memory_create,
            commands::deep::deep_memory_read,
            commands::deep::deep_memory_update,
            commands::deep::deep_memory_delete,
            commands::deep::deep_memory_search,
            commands::deep::deep_memory_query,
            commands::deep::deep_memory_feedback,
            commands::deep::deep_memory_export_bundle,
            commands::deep::deep_memory_import_bundle,
            commands::deep::deep_memory_get_migration_report,
            commands::deep::deep_memory_list_groups,
            commands::deep::deep_memory_create_group,
            commands::deep::deep_memory_delete_group,
            // Command (Slash Commands) marketplace commands
            commands::deep::deep_command_list,
            commands::deep::deep_command_install,
            commands::deep::deep_command_uninstall,
            commands::deep::deep_command_get_content,
            commands::deep::deep_command_create,
            // Subagent commands
            commands::subagent::deep_subagent_list,
            commands::subagent::deep_subagent_install,
            commands::subagent::deep_subagent_uninstall,
            commands::subagent::deep_subagent_is_installed,
            commands::subagent::deep_subagent_get,
            commands::subagent::deep_subagent_create,
            // Connector commands
            commands::connectors::discover_connectors,
            commands::connectors::install_connector,
            commands::connectors::uninstall_connector,
            commands::connectors::connect_connector,
            commands::connectors::disconnect_connector,
            commands::connectors::reconnect_connector,
            commands::connectors::configure_connector_secrets,
            commands::connectors::get_connector_secrets_status,
            commands::connectors::get_connector_status,
            commands::connectors::create_connector,
            commands::connectors::connector_call_tool,
            commands::connectors::get_all_connector_tools,
            commands::connectors::get_all_connector_states,
            commands::connectors::connect_all_connectors,
            commands::connectors::disconnect_all_connectors,
            // OAuth commands
            commands::connectors::start_connector_oauth_flow,
            commands::connectors::poll_oauth_device_code,
            commands::connectors::get_oauth_status,
            commands::connectors::refresh_oauth_tokens,
            commands::connectors::revoke_oauth_tokens,
            // MCP Apps commands
            commands::connectors::get_connector_apps,
            commands::connectors::get_connector_app_content,
            commands::connectors::call_connector_app_tool,
            // Integration commands
            commands::integrations::agent_integration_list_statuses,
            commands::integrations::agent_integration_connect,
            commands::integrations::agent_integration_recover_whatsapp,
            commands::integrations::agent_integration_disconnect,
            commands::integrations::agent_integration_get_qr,
            commands::integrations::agent_integration_configure,
            commands::integrations::agent_integration_get_config,
            commands::integrations::agent_integration_get_settings,
            commands::integrations::agent_integration_update_settings,
            commands::integrations::agent_integration_send_test,
            // Remote access commands
            commands::remote_access::remote_access_get_status,
            commands::remote_access::remote_access_enable,
            commands::remote_access::remote_access_disable,
            commands::remote_access::remote_access_generate_qr,
            commands::remote_access::remote_access_list_devices,
            commands::remote_access::remote_access_revoke_device,
            commands::remote_access::remote_access_set_public_base_url,
            commands::remote_access::remote_access_set_tunnel_mode,
            commands::remote_access::remote_access_set_tunnel_options,
            commands::remote_access::remote_access_refresh_tunnel,
            commands::remote_access::remote_access_install_tunnel_binary,
            commands::remote_access::remote_access_authenticate_tunnel,
            commands::remote_access::remote_access_start_tunnel,
            commands::remote_access::remote_access_stop_tunnel,
            commands::remote_access::remote_access_delete_all,
            // Service lifecycle commands
            commands::service::service_get_mode,
            commands::service::service_set_mode,
            commands::service::service_status,
            commands::service::service_install,
            commands::service::service_uninstall,
            commands::service::service_start,
            commands::service::service_stop,
            commands::service::service_restart,
        ])
        .setup(|app| {
            // Auto-update disabled until a proper signing key pair is configured
            let _ = app;
            commands::credentials::credentials_migrate_on_startup()
                .map_err(|error| format!("Credential migration failed during startup: {}", error))?;

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
