/**
 * AGENTS.md Templates
 *
 * Templates for generating AGENTS.md files from project information
 */

import type { ProjectInfo, DirectoryInfo, TechStack, ProjectCommand } from './types.js';

/**
 * Generate AGENTS.md content from project info
 */
export function generateAgentsMd(info: ProjectInfo): string {
  const sections: string[] = [];

  // Header
  sections.push(`# AGENTS.md - ${info.name}`);
  sections.push('');
  sections.push('> Auto-generated by Gemini Cowork. Edit sections below to customize agent behavior.');
  sections.push('');

  // Project Overview
  sections.push('## Project Overview');
  sections.push('');
  sections.push(generateOverview(info));
  sections.push('');

  // Tech Stack
  sections.push('## Tech Stack');
  sections.push('');
  sections.push(generateTechStackTable(info.techStack));
  sections.push('');

  // Directory Structure
  sections.push('## Directory Structure');
  sections.push('');
  sections.push('```');
  sections.push(generateDirectoryTree(info.structure, info.name));
  sections.push('```');
  sections.push('');

  // Available Commands
  if (info.commands.length > 0) {
    sections.push('## Available Commands');
    sections.push('');
    sections.push(generateCommandsTable(info.commands));
    sections.push('');
  }

  // Coding Conventions
  sections.push('## Coding Conventions');
  sections.push('');
  sections.push(generateConventions(info));
  sections.push('');

  // Agent Instructions
  sections.push('## Agent Instructions');
  sections.push('');
  sections.push(generateInstructions(info));
  sections.push('');

  // Important Files
  if (info.importantFiles.length > 0) {
    sections.push('## Important Files');
    sections.push('');
    for (const file of info.importantFiles) {
      sections.push(`- \`${file.path}\` - ${file.description}`);
    }
    sections.push('');
  }

  // Environment Setup
  sections.push('## Environment Setup');
  sections.push('');
  sections.push(generateEnvironmentSetup(info));
  sections.push('');

  // Additional Context
  sections.push('## Additional Context');
  sections.push('');
  sections.push('[Add any project-specific notes, architecture decisions, or context here]');
  sections.push('');

  return sections.join('\n');
}

/**
 * Generate project overview text
 */
function generateOverview(info: ProjectInfo): string {
  const parts: string[] = [];

  // Basic description
  parts.push(`${info.name} is a ${info.techStack.language} project`);

  if (info.techStack.framework) {
    parts[0] += ` using ${info.techStack.framework}`;
  }

  parts[0] += '.';

  // Add pattern information
  if (info.detectedPatterns.length > 0) {
    parts.push('');
    parts.push(`**Architecture:** ${info.detectedPatterns.join(', ')}`);
  }

  return parts.join('\n');
}

/**
 * Generate tech stack table
 */
function generateTechStackTable(techStack: TechStack): string {
  const rows: string[] = [];

  rows.push('| Component | Technology |');
  rows.push('|-----------|------------|');
  rows.push(`| Language | ${techStack.language} |`);

  if (techStack.framework) {
    rows.push(`| Framework | ${techStack.framework} |`);
  }

  if (techStack.buildTool) {
    rows.push(`| Build Tool | ${techStack.buildTool} |`);
  }

  if (techStack.packageManager) {
    rows.push(`| Package Manager | ${techStack.packageManager} |`);
  }

  if (techStack.testFramework) {
    rows.push(`| Test Framework | ${techStack.testFramework} |`);
  }

  if (techStack.additional) {
    for (const [key, value] of Object.entries(techStack.additional)) {
      rows.push(`| ${key} | ${value} |`);
    }
  }

  return rows.join('\n');
}

/**
 * Generate directory tree
 */
function generateDirectoryTree(structure: DirectoryInfo[], rootName: string): string {
  const lines: string[] = [];
  lines.push(`${rootName}/`);

  const renderDir = (dirs: DirectoryInfo[], _prefix: string, isLast: boolean[] = []) => {
    for (let i = 0; i < dirs.length; i++) {
      const dir = dirs[i];
      const isLastItem = i === dirs.length - 1;

      // Build prefix for this line
      let linePrefix = '';
      for (let j = 0; j < isLast.length; j++) {
        linePrefix += isLast[j] ? '    ' : '│   ';
      }
      linePrefix += isLastItem ? '└── ' : '├── ';

      // Add directory line with description
      const desc = dir.description ? ` # ${dir.description}` : '';
      lines.push(`${linePrefix}${dir.name}/${desc}`);

      // Render children
      if (dir.children && dir.children.length > 0) {
        renderDir(dir.children, '', [...isLast, isLastItem]);
      }
    }
  };

  if (structure.length > 0) {
    renderDir(structure, '', []);
  }

  return lines.join('\n');
}

/**
 * Generate commands table
 */
function generateCommandsTable(commands: ProjectCommand[]): string {
  const rows: string[] = [];

  rows.push('| Command | Description | Usage |');
  rows.push('|---------|-------------|-------|');

  for (const cmd of commands.slice(0, 15)) { // Limit to 15 commands
    rows.push(`| \`${cmd.command}\` | ${cmd.description} | ${cmd.usage} |`);
  }

  if (commands.length > 15) {
    rows.push('');
    rows.push(`*...and ${commands.length - 15} more commands*`);
  }

  return rows.join('\n');
}

/**
 * Generate coding conventions section
 */
function generateConventions(info: ProjectInfo): string {
  const sections: string[] = [];

  // Style Guide
  sections.push('### Style Guide');
  if (info.conventions.length > 0) {
    for (const conv of info.conventions) {
      sections.push(`- ${conv}`);
    }
  } else {
    sections.push('- Follow existing code patterns and conventions');
    sections.push('- Use consistent formatting throughout the codebase');
  }
  sections.push('');

  // Naming Conventions
  sections.push('### Naming Conventions');
  sections.push('- Files: [kebab-case/camelCase - detect from existing files]');
  sections.push('- Functions: [camelCase/snake_case - detect from existing code]');
  sections.push('- Components: [PascalCase]');
  sections.push('- Constants: [UPPER_SNAKE_CASE]');
  sections.push('');

  // Patterns
  sections.push('### Patterns');
  if (info.detectedPatterns.length > 0) {
    for (const pattern of info.detectedPatterns) {
      sections.push(`- ${pattern}`);
    }
  } else {
    sections.push('- [Detected patterns will be listed here]');
  }

  return sections.join('\n');
}

/**
 * Generate agent instructions section
 */
function generateInstructions(_info: ProjectInfo): string {
  const sections: string[] = [];

  sections.push('### Do');
  sections.push('- Follow existing code patterns and conventions');
  sections.push("- Use the project's established utilities and helpers");
  sections.push('- Write tests for new functionality');
  sections.push('- Keep changes minimal and focused');
  sections.push('- Use TypeScript types when available');
  sections.push('');

  sections.push("### Don't");
  sections.push('- Introduce new dependencies without discussion');
  sections.push('- Change existing APIs without migration plan');
  sections.push('- Skip error handling');
  sections.push('- Over-engineer solutions');
  sections.push('- Add unnecessary comments or documentation');

  return sections.join('\n');
}

/**
 * Generate environment setup section
 */
function generateEnvironmentSetup(info: ProjectInfo): string {
  const lines: string[] = [];

  lines.push('```bash');
  lines.push('# Required environment variables');
  lines.push('# Copy .env.example to .env and fill in values');
  lines.push('');
  lines.push('# API_KEY=your_api_key_here');
  lines.push('# DATABASE_URL=your_database_url');
  lines.push('```');
  lines.push('');
  lines.push('**Setup steps:**');

  // Add setup steps based on tech stack
  if (info.techStack.packageManager) {
    const pm = info.techStack.packageManager;
    if (pm === 'npm' || pm === 'yarn' || pm === 'pnpm' || pm === 'bun') {
      lines.push(`1. Install dependencies: \`${pm} install\``);
    } else if (pm === 'pip') {
      lines.push('1. Install dependencies: `pip install -r requirements.txt`');
    } else if (pm === 'cargo') {
      lines.push('1. Build: `cargo build`');
    }
  }

  lines.push('2. Copy `.env.example` to `.env` and configure');
  lines.push('3. Run development server (see Available Commands)');

  return lines.join('\n');
}

/**
 * Generate minimal AGENTS.md for quick start
 */
export function generateMinimalAgentsMd(projectName: string, language: string): string {
  return `# AGENTS.md - ${projectName}

## Project Overview

${projectName} is a ${language} project.

## Tech Stack

| Component | Technology |
|-----------|------------|
| Language | ${language} |

## Agent Instructions

### Do
- Follow existing code patterns
- Keep changes minimal and focused

### Don't
- Over-engineer solutions
- Skip error handling
`;
}

/**
 * Generate AGENTS.md section for updates
 */
export function generateSection(
  sectionName: string,
  content: Record<string, unknown>
): string {
  switch (sectionName) {
    case 'tech_stack':
      return generateTechStackTable(content as unknown as TechStack);
    case 'commands':
      return generateCommandsTable(content as unknown as ProjectCommand[]);
    default:
      return JSON.stringify(content, null, 2);
  }
}
