export interface SettingHelpEntry {
  id: string;
  title: string;
  description: string;
  what_it_controls: string;
  when_to_use: string;
  tool_impact: string[];
  security_notes: string;
  requires_new_session: boolean;
}

export const SETTINGS_HELP_CONTENT: SettingHelpEntry[] = [
  {
    id: 'provider.activeProvider',
    title: 'Active Provider',
    description: 'Selects which model provider handles chat and most native capabilities.',
    what_it_controls:
      'Switches runtime provider context, provider-scoped model catalogs, and provider-native capabilities.',
    when_to_use:
      'Change this when you want to use different model families, pricing, or provider-native features.',
    tool_impact: ['chat', 'web_search', 'google_grounded_search', 'computer_use', 'web_fetch'],
    security_notes: 'Provider-specific credentials are required and stored in system credential storage.',
    requires_new_session: true,
  },
  {
    id: 'provider.apiKey',
    title: 'Provider API Key',
    description: 'Authenticates requests to the active provider for chat and provider-native tools.',
    what_it_controls:
      'Enables provider runtime access for chat and related tools. Missing keys disable provider-backed operations.',
    when_to_use: 'Set when first configuring a provider, rotate keys, or troubleshoot auth failures.',
    tool_impact: ['chat', 'web_search', 'google_grounded_search', 'web_fetch', 'computer_use'],
    security_notes: 'Never share keys in chats or screenshots. Keys are masked and stored securely.',
    requires_new_session: false,
  },
  {
    id: 'provider.baseUrl',
    title: 'Provider Base URL',
    description: 'Overrides the provider API endpoint (for compatible hosts and local gateways).',
    what_it_controls:
      'Directs API traffic to a custom endpoint for providers that support configurable base URLs.',
    when_to_use: 'Use for proxy endpoints, enterprise gateways, or local provider-compatible servers.',
    tool_impact: ['chat', 'provider-native tools'],
    security_notes: 'Only use trusted endpoints to avoid leaking prompts or credentials.',
    requires_new_session: true,
  },
  {
    id: 'provider.chatModel',
    title: 'Chat Model',
    description: 'Defines the default model ID used for conversation turns.',
    what_it_controls: 'Determines response quality, latency, context size, and model-specific behavior.',
    when_to_use: 'Adjust when you need stronger reasoning, lower latency, or lower usage cost.',
    tool_impact: ['chat', 'task planning'],
    security_notes: 'Model IDs are harmless; changing model can alter output style and reliability.',
    requires_new_session: true,
  },
  {
    id: 'media.imageBackend',
    title: 'Image Backend',
    description: 'Selects the backend used for image generation and image editing.',
    what_it_controls: 'Routes generate_image and edit_image calls to Google, OpenAI, or Fal backends.',
    when_to_use: 'Switch for quality preferences, pricing, or key availability.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Requires matching backend key to be configured for reliable execution.',
    requires_new_session: false,
  },
  {
    id: 'media.videoBackend',
    title: 'Video Backend',
    description: 'Selects the backend used for video generation.',
    what_it_controls: 'Routes generate_video calls to Google, OpenAI, or Fal backends.',
    when_to_use: 'Switch for output style, cost, or backend availability.',
    tool_impact: ['generate_video'],
    security_notes: 'Ensure the selected backend key is configured before use.',
    requires_new_session: false,
  },
  {
    id: 'media.googleApiKey',
    title: 'Google Media API Key',
    description: 'Authorizes Google-backed media tools and Google media fallbacks.',
    what_it_controls: 'Unlocks Google image/video generation when Google is the selected backend.',
    when_to_use: 'Required when using Google for image or video generation.',
    tool_impact: ['generate_image', 'edit_image', 'generate_video'],
    security_notes: 'Store and rotate like any production credential.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiApiKey',
    title: 'OpenAI Media API Key',
    description: 'Authorizes OpenAI-backed media operations.',
    what_it_controls: 'Unlocks OpenAI image/video generation paths in media routing.',
    when_to_use: 'Required for OpenAI media backend unless provider key fallback applies.',
    tool_impact: ['generate_image', 'edit_image', 'generate_video', 'analyze_video'],
    security_notes: 'Avoid exposing keys in logs or clipboard history.',
    requires_new_session: false,
  },
  {
    id: 'media.falApiKey',
    title: 'Fal Media API Key',
    description: 'Authorizes Fal-backed image and video generation operations.',
    what_it_controls: 'Enables Fal routing for generation endpoints configured in specialized model overrides.',
    when_to_use: 'Required if Fal is selected for image and/or video generation.',
    tool_impact: ['generate_image', 'generate_video'],
    security_notes: 'Use least-privileged keys and rotate periodically.',
    requires_new_session: false,
  },
  {
    id: 'media.googleImageModel',
    title: 'Google Image Model',
    description: 'Override for Google image generation model ID.',
    what_it_controls: 'Changes which Google model powers image generation.',
    when_to_use: 'Use when testing upgrades, compatibility, or quality differences.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Invalid IDs can fail generation calls.',
    requires_new_session: false,
  },
  {
    id: 'media.googleVideoModel',
    title: 'Google Video Model',
    description: 'Override for Google video generation model ID.',
    what_it_controls: 'Changes which Google model powers video generation.',
    when_to_use: 'Use for controlled rollouts of new video models.',
    tool_impact: ['generate_video'],
    security_notes: 'Prefer validated model IDs to reduce runtime failures.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiImageModel',
    title: 'OpenAI Image Model',
    description: 'Override for OpenAI image model ID.',
    what_it_controls: 'Selects OpenAI model used when OpenAI image backend is active.',
    when_to_use: 'Use when moving between model generations or testing behavior.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Unsupported IDs can disable image generation.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiVideoModel',
    title: 'OpenAI Video Model',
    description: 'Override for OpenAI video model ID.',
    what_it_controls: 'Selects OpenAI model used for video generation with OpenAI backend.',
    when_to_use: 'Use when evaluating speed/quality tradeoffs.',
    tool_impact: ['generate_video'],
    security_notes: 'Model availability may vary by account/region.',
    requires_new_session: false,
  },
  {
    id: 'media.falImageModel',
    title: 'Fal Image Model',
    description: 'Override for Fal image model ID.',
    what_it_controls: 'Changes the Fal image model used by generate_image.',
    when_to_use: 'Use for Fal model experiments and upgrades.',
    tool_impact: ['generate_image'],
    security_notes: 'Verify billing and quota policies for the model.',
    requires_new_session: false,
  },
  {
    id: 'media.falVideoModel',
    title: 'Fal Video Model',
    description: 'Override for Fal video model ID.',
    what_it_controls: 'Changes the Fal video model used by generate_video.',
    when_to_use: 'Use for specific Fal video capability requirements.',
    tool_impact: ['generate_video'],
    security_notes: 'Model ID mismatch leads to immediate tool failures.',
    requires_new_session: false,
  },
  {
    id: 'integration.externalSearchProvider',
    title: 'External Search Fallback Provider',
    description: 'Chooses search fallback when provider-native search is unavailable.',
    what_it_controls: 'Routes web_search fallback to Google, Exa, or Tavily.',
    when_to_use: 'Use when your active provider has limited native web search support.',
    tool_impact: ['web_search', 'google_grounded_search'],
    security_notes: 'Fallback providers may have separate data handling policies.',
    requires_new_session: false,
  },
  {
    id: 'integration.exaApiKey',
    title: 'Exa API Key',
    description: 'Credential for Exa-powered web search fallback.',
    what_it_controls: 'Enables Exa backend for search fallback when selected.',
    when_to_use: 'Set when external search provider is Exa.',
    tool_impact: ['web_search'],
    security_notes: 'Treat as sensitive credential and rotate periodically.',
    requires_new_session: false,
  },
  {
    id: 'integration.tavilyApiKey',
    title: 'Tavily API Key',
    description: 'Credential for Tavily-powered web search fallback.',
    what_it_controls: 'Enables Tavily backend for search fallback when selected.',
    when_to_use: 'Set when external search provider is Tavily.',
    tool_impact: ['web_search'],
    security_notes: 'Key leakage can consume quota; keep private.',
    requires_new_session: false,
  },
  {
    id: 'integration.stitchApiKey',
    title: 'Stitch MCP API Key',
    description: 'Controls availability of Stitch MCP and Stitch-labeled design tools.',
    what_it_controls: 'If absent, stitch/mcp stitch tools are not registered for use.',
    when_to_use: 'Set when using Stitch-driven design or MCP functionality.',
    tool_impact: ['mcp_*', 'stitch*'],
    security_notes: 'Stored securely; missing key is safer than stale leaked key.',
    requires_new_session: false,
  },
  {
    id: 'integration.computerUseModel',
    title: 'Computer Use Model',
    description: 'Model ID used by computer_use browser automation tooling.',
    what_it_controls: 'Changes backend model used for autonomous browser tasks.',
    when_to_use: 'Adjust when evaluating capability/performance changes.',
    tool_impact: ['computer_use'],
    security_notes: 'Model behavior influences automation reliability.',
    requires_new_session: false,
  },
  {
    id: 'integration.deepResearchModel',
    title: 'Deep Research Model',
    description: 'Model ID used for deep_research workflows.',
    what_it_controls: 'Defines the long-running research engine model.',
    when_to_use: 'Adjust when testing output quality or cost differences.',
    tool_impact: ['deep_research'],
    security_notes: 'Long-running jobs may consume more quota.',
    requires_new_session: false,
  },
  {
    id: 'integration.sharedSessionWorkingDirectory',
    title: 'Shared Integration Working Directory',
    description: 'Default working directory for integration-triggered shared sessions.',
    what_it_controls: 'Sets filesystem root context for WhatsApp/Slack/Telegram shared sessions.',
    when_to_use: 'Set to your primary workspace for predictable file tool behavior.',
    tool_impact: ['read_any_file', 'file tools', 'shell tools in shared sessions'],
    security_notes: 'Choose directories with only data you want integrations to access.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.connection',
    title: 'WhatsApp Connection',
    description: 'Connects a WhatsApp identity to receive/send integration messages.',
    what_it_controls: 'Enables WhatsApp-based shared session messaging and notifications.',
    when_to_use: 'Enable for chat-based remote control or notifications through WhatsApp.',
    tool_impact: ['send_notification_whatsapp', 'shared-session ingress'],
    security_notes: 'Use a dedicated account/number for operational safety.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.allowlist',
    title: 'WhatsApp Sender Allowlist',
    description: 'Restricts which phone numbers can trigger the agent.',
    what_it_controls: 'Blocks unauthorized senders before they reach agent execution.',
    when_to_use: 'Always keep allowlist tight in production-like setups.',
    tool_impact: ['shared-session ingress policy'],
    security_notes: 'Primary safety boundary for WhatsApp ingress.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.denialMessage',
    title: 'WhatsApp Denial Message',
    description: 'Reply sent to unauthorized senders.',
    what_it_controls: 'User-facing rejection text for blocked numbers.',
    when_to_use: 'Customize messaging tone while keeping security intent clear.',
    tool_impact: ['shared-session ingress policy'],
    security_notes: 'Avoid revealing internal system details in denial responses.',
    requires_new_session: false,
  },
  {
    id: 'slack.connection',
    title: 'Slack Connection',
    description: 'Connects Slack bot tokens for Slack-based messaging integration.',
    what_it_controls: 'Enables Slack messaging ingress and notification tools.',
    when_to_use: 'Enable when teams coordinate tasks from Slack.',
    tool_impact: ['send_notification_slack', 'shared-session ingress'],
    security_notes: 'Use scoped tokens and minimal channel access.',
    requires_new_session: false,
  },
  {
    id: 'slack.botToken',
    title: 'Slack Bot Token',
    description: 'Bot OAuth token used for Slack API calls.',
    what_it_controls: 'Authorizes bot messaging and channel operations.',
    when_to_use: 'Required for Slack connector authentication.',
    tool_impact: ['send_notification_slack', 'slack inbound/outbound'],
    security_notes: 'Treat as secret; rotate immediately if exposed.',
    requires_new_session: false,
  },
  {
    id: 'slack.appToken',
    title: 'Slack App Token',
    description: 'App-level token for socket/event connectivity.',
    what_it_controls: 'Required for real-time connection lifecycle in Slack integration.',
    when_to_use: 'Set alongside bot token for stable Slack connectivity.',
    tool_impact: ['slack inbound/outbound'],
    security_notes: 'Keep token private and scope to required capabilities.',
    requires_new_session: false,
  },
  {
    id: 'telegram.connection',
    title: 'Telegram Connection',
    description: 'Connects Telegram bot for messaging integration.',
    what_it_controls: 'Enables Telegram message ingress and outbound notifications.',
    when_to_use: 'Enable when Telegram is used as operator/control channel.',
    tool_impact: ['send_notification_telegram', 'shared-session ingress'],
    security_notes: 'Use dedicated bot token and restrict bot visibility where possible.',
    requires_new_session: false,
  },
  {
    id: 'telegram.botToken',
    title: 'Telegram Bot Token',
    description: 'Bot token generated from BotFather for Telegram API access.',
    what_it_controls: 'Authenticates Telegram bot connectivity and messaging.',
    when_to_use: 'Required for Telegram connector setup.',
    tool_impact: ['send_notification_telegram', 'telegram inbound/outbound'],
    security_notes: 'Leakage gives bot-level control; rotate if compromised.',
    requires_new_session: false,
  },
];

export const SETTINGS_HELP_BY_ID: Record<string, SettingHelpEntry> = SETTINGS_HELP_CONTENT.reduce(
  (acc, entry) => {
    acc[entry.id] = entry;
    return acc;
  },
  {} as Record<string, SettingHelpEntry>,
);

export function getSettingHelp(settingId: string): SettingHelpEntry | undefined {
  return SETTINGS_HELP_BY_ID[settingId];
}
