export interface SettingHelpEntry {
  id: string;
  title: string;
  description: string;
  what_it_controls: string;
  when_to_use: string;
  tool_impact: string[];
  security_notes: string;
  requires_new_session: boolean;
}

export const SETTINGS_HELP_CONTENT: SettingHelpEntry[] = [
  {
    id: 'provider.activeProvider',
    title: 'Active Provider',
    description: 'Selects which model provider handles chat and most native capabilities.',
    what_it_controls:
      'Switches runtime provider context, provider-scoped model catalogs, and provider-native capabilities.',
    when_to_use:
      'Change this when you want to use different model families, pricing, or provider-native features.',
    tool_impact: ['chat', 'web_search', 'google_grounded_search', 'computer_use', 'web_fetch'],
    security_notes: 'Provider-specific credentials are required and stored in system credential storage.',
    requires_new_session: true,
  },
  {
    id: 'provider.apiKey',
    title: 'Provider API Key',
    description: 'Authenticates requests to the active provider for chat and provider-native tools.',
    what_it_controls:
      'Enables provider runtime access for chat and related tools. Missing keys disable provider-backed operations.',
    when_to_use: 'Set when first configuring a provider, rotate keys, or troubleshoot auth failures.',
    tool_impact: ['chat', 'web_search', 'google_grounded_search', 'web_fetch', 'computer_use'],
    security_notes: 'Never share keys in chats or screenshots. Keys are masked and stored securely.',
    requires_new_session: false,
  },
  {
    id: 'provider.baseUrl',
    title: 'Provider Base URL',
    description: 'Overrides the provider API endpoint (for compatible hosts and local gateways).',
    what_it_controls:
      'Directs API traffic to a custom endpoint for providers that support configurable base URLs.',
    when_to_use: 'Use for proxy endpoints, enterprise gateways, or local provider-compatible servers.',
    tool_impact: ['chat', 'provider-native tools'],
    security_notes: 'Only use trusted endpoints to avoid leaking prompts or credentials.',
    requires_new_session: true,
  },
  {
    id: 'provider.chatModel',
    title: 'Chat Model',
    description: 'Defines the default model ID used for conversation turns.',
    what_it_controls: 'Determines response quality, latency, context size, and model-specific behavior.',
    when_to_use: 'Adjust when you need stronger reasoning, lower latency, or lower usage cost.',
    tool_impact: ['chat', 'task planning'],
    security_notes: 'Model IDs are harmless; changing model can alter output style and reliability.',
    requires_new_session: true,
  },
  {
    id: 'provider.commandSandbox.mode',
    title: 'Command Sandbox Mode',
    description: 'Sets technical enforcement level for shell command execution.',
    what_it_controls:
      'Defines whether shell execution is read-only, workspace-write, or unrestricted (danger-full-access), including shell/tool nodes inside workflow runs.',
    when_to_use:
      'Use read-only for planning/audits, workspace-write for normal coding, and danger-full-access only for trusted advanced workflows.',
    tool_impact: ['execute', 'Bash', 'shell_execute permission flow'],
    security_notes: 'danger-full-access removes core safety boundaries and should be temporary.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.allowNetwork',
    title: 'Sandbox Network Access',
    description: 'Controls whether shell commands can access the network.',
    what_it_controls:
      'Blocks/permits commands like curl, wget, ssh, ping and similar network operations, including networked shell commands triggered by workflows.',
    when_to_use: 'Enable only when the task explicitly requires network access from shell commands.',
    tool_impact: ['execute', 'Bash'],
    security_notes: 'Keeping network off reduces exfiltration and remote-command risk.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.allowProcessSpawn',
    title: 'Sandbox Process Spawn',
    description: 'Controls whether commands that spawn subprocesses are allowed.',
    what_it_controls: 'Blocks pipelines/subshell patterns when disabled.',
    when_to_use: 'Disable in high-security sessions or when running untrusted tasks.',
    tool_impact: ['execute', 'Bash'],
    security_notes: 'Disabling process spawn limits chained command behavior.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.allowedPaths',
    title: 'Sandbox Allowed Paths',
    description: 'Additional filesystem roots shell commands may access.',
    what_it_controls: 'Expands command path scope beyond the current working directory.',
    when_to_use: 'Add only paths you trust the agent to read/write via shell operations.',
    tool_impact: ['execute', 'Bash', 'path validation'],
    security_notes: 'Overly broad roots reduce sandbox effectiveness.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.deniedPaths',
    title: 'Sandbox Denied Paths',
    description: 'Filesystem roots always blocked for shell commands.',
    what_it_controls: 'Hard-denies command access even when allowed roots are broad.',
    when_to_use: 'Use to protect sensitive directories like system/config/credential locations.',
    tool_impact: ['execute', 'Bash', 'path validation'],
    security_notes: 'Prefer explicit denied paths for secrets and system-critical directories.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.trustedCommands',
    title: 'Trusted Command Prefixes',
    description: 'Commands eligible for automatic approval in auto mode when sandbox-allowed.',
    what_it_controls: 'Approval-layer auto-allow behavior for shell requests.',
    when_to_use: 'Add low-risk read commands used frequently; keep list minimal.',
    tool_impact: ['shell_execute permission flow'],
    security_notes: 'Only include commands safe to run without prompting.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.maxExecutionTimeMs',
    title: 'Max Command Runtime (ms)',
    description: 'Maximum duration a shell command can run before termination.',
    what_it_controls: 'Stops long-running or hanging commands after timeout.',
    when_to_use: 'Tune for heavy builds vs. strict runtime control.',
    tool_impact: ['execute', 'Bash'],
    security_notes: 'Lower limits reduce abuse but can interrupt legitimate long tasks.',
    requires_new_session: false,
  },
  {
    id: 'provider.commandSandbox.maxOutputBytes',
    title: 'Max Command Output Bytes',
    description: 'Caps command stdout/stderr captured by the app.',
    what_it_controls: 'Prevents oversized terminal output from overwhelming memory/UI.',
    when_to_use: 'Increase for verbose tooling, decrease for strict resource limits.',
    tool_impact: ['execute', 'Bash'],
    security_notes: 'Lower caps reduce risk from noisy or malicious outputs.',
    requires_new_session: false,
  },
  {
    id: 'media.imageBackend',
    title: 'Image Backend',
    description: 'Selects the backend used for image generation and image editing.',
    what_it_controls: 'Routes generate_image and edit_image calls to Google, OpenAI, or Fal backends.',
    when_to_use: 'Switch for quality preferences, pricing, or key availability.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Requires matching backend key to be configured for reliable execution.',
    requires_new_session: false,
  },
  {
    id: 'media.videoBackend',
    title: 'Video Backend',
    description: 'Selects the backend used for video generation.',
    what_it_controls: 'Routes generate_video calls to Google, OpenAI, or Fal backends.',
    when_to_use: 'Switch for output style, cost, or backend availability.',
    tool_impact: ['generate_video'],
    security_notes: 'Ensure the selected backend key is configured before use.',
    requires_new_session: false,
  },
  {
    id: 'media.googleApiKey',
    title: 'Google Media API Key',
    description: 'Authorizes Google-backed media tools and Google media fallbacks.',
    what_it_controls: 'Unlocks Google image/video generation when Google is the selected backend.',
    when_to_use: 'Required when using Google for image or video generation.',
    tool_impact: ['generate_image', 'edit_image', 'generate_video'],
    security_notes: 'Store and rotate like any production credential.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiApiKey',
    title: 'OpenAI Media API Key',
    description: 'Authorizes OpenAI-backed media operations.',
    what_it_controls: 'Unlocks OpenAI image/video generation paths in media routing.',
    when_to_use: 'Required for OpenAI media backend unless provider key fallback applies.',
    tool_impact: ['generate_image', 'edit_image', 'generate_video', 'analyze_video'],
    security_notes: 'Avoid exposing keys in logs or clipboard history.',
    requires_new_session: false,
  },
  {
    id: 'media.falApiKey',
    title: 'Fal Media API Key',
    description: 'Authorizes Fal-backed image and video generation operations.',
    what_it_controls: 'Enables Fal routing for generation endpoints configured in specialized model overrides.',
    when_to_use: 'Required if Fal is selected for image and/or video generation.',
    tool_impact: ['generate_image', 'generate_video'],
    security_notes: 'Use least-privileged keys and rotate periodically.',
    requires_new_session: false,
  },
  {
    id: 'media.googleImageModel',
    title: 'Google Image Model',
    description: 'Override for Google image generation model ID.',
    what_it_controls: 'Changes which Google model powers image generation.',
    when_to_use: 'Use when testing upgrades, compatibility, or quality differences.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Invalid IDs can fail generation calls.',
    requires_new_session: false,
  },
  {
    id: 'media.googleVideoModel',
    title: 'Google Video Model',
    description: 'Override for Google video generation model ID.',
    what_it_controls: 'Changes which Google model powers video generation.',
    when_to_use: 'Use for controlled rollouts of new video models.',
    tool_impact: ['generate_video'],
    security_notes: 'Prefer validated model IDs to reduce runtime failures.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiImageModel',
    title: 'OpenAI Image Model',
    description: 'Override for OpenAI image model ID.',
    what_it_controls: 'Selects OpenAI model used when OpenAI image backend is active.',
    when_to_use: 'Use when moving between model generations or testing behavior.',
    tool_impact: ['generate_image', 'edit_image'],
    security_notes: 'Unsupported IDs can disable image generation.',
    requires_new_session: false,
  },
  {
    id: 'media.openaiVideoModel',
    title: 'OpenAI Video Model',
    description: 'Override for OpenAI video model ID.',
    what_it_controls: 'Selects OpenAI model used for video generation with OpenAI backend.',
    when_to_use: 'Use when evaluating speed/quality tradeoffs.',
    tool_impact: ['generate_video'],
    security_notes: 'Model availability may vary by account/region.',
    requires_new_session: false,
  },
  {
    id: 'media.falImageModel',
    title: 'Fal Image Model',
    description: 'Override for Fal image model ID.',
    what_it_controls: 'Changes the Fal image model used by generate_image.',
    when_to_use: 'Use for Fal model experiments and upgrades.',
    tool_impact: ['generate_image'],
    security_notes: 'Verify billing and quota policies for the model.',
    requires_new_session: false,
  },
  {
    id: 'media.falVideoModel',
    title: 'Fal Video Model',
    description: 'Override for Fal video model ID.',
    what_it_controls: 'Changes the Fal video model used by generate_video.',
    when_to_use: 'Use for specific Fal video capability requirements.',
    tool_impact: ['generate_video'],
    security_notes: 'Model ID mismatch leads to immediate tool failures.',
    requires_new_session: false,
  },
  {
    id: 'capability.policyControl',
    title: 'Capability Policy Control',
    description:
      'Unified capability table for availability status and per-tool Allow/Ask/Deny policy.',
    what_it_controls:
      'Shows whether each capability is currently available and lets you set policy action inline for each tool.',
    when_to_use:
      'Use when you want one place to audit capability readiness and tighten/relax permissions.',
    tool_impact: ['all capability tools', 'policy_evaluate'],
    security_notes:
      'Changing policy from Ask to Allow reduces review prompts; use Allow only for tools you trust.',
    requires_new_session: false,
  },
  {
    id: 'integration.externalSearchProvider',
    title: 'External Search Fallback Provider',
    description: 'Chooses runtime search fallback when provider-native search is unavailable.',
    what_it_controls: 'Routes web_search fallback to Google, Exa, or Tavily.',
    when_to_use: 'Use from the Runtime tab when your active provider has limited native web search support.',
    tool_impact: ['web_search', 'google_grounded_search'],
    security_notes: 'Fallback providers may have separate data handling policies.',
    requires_new_session: false,
  },
  {
    id: 'integration.exaApiKey',
    title: 'Exa API Key',
    description: 'Credential for Exa-powered web search fallback.',
    what_it_controls: 'Enables Exa backend for search fallback when selected.',
    when_to_use: 'Set from Runtime tab when external search provider is Exa.',
    tool_impact: ['web_search'],
    security_notes: 'Treat as sensitive credential and rotate periodically.',
    requires_new_session: false,
  },
  {
    id: 'integration.tavilyApiKey',
    title: 'Tavily API Key',
    description: 'Credential for Tavily-powered web search fallback.',
    what_it_controls: 'Enables Tavily backend for search fallback when selected.',
    when_to_use: 'Set from Runtime tab when external search provider is Tavily.',
    tool_impact: ['web_search'],
    security_notes: 'Key leakage can consume quota; keep private.',
    requires_new_session: false,
  },
  {
    id: 'integration.stitchApiKey',
    title: 'Stitch MCP API Key',
    description: 'Controls availability of Stitch MCP and Stitch-labeled design tools.',
    what_it_controls: 'If absent, stitch/mcp stitch tools are not registered for use.',
    when_to_use: 'Set from Runtime tab when using Stitch-driven design or MCP functionality.',
    tool_impact: ['mcp_*', 'stitch*'],
    security_notes: 'Stored securely; missing key is safer than stale leaked key.',
    requires_new_session: false,
  },
  {
    id: 'integration.externalCli.enableTools',
    title: 'External CLI Tool Enablement',
    description: 'Enables external Codex/Claude orchestration tools when binaries are installed.',
    what_it_controls:
      'Registers or hides start/progress/respond/cancel external CLI tools for each installed provider.',
    when_to_use:
      'Enable from Runtime tab for users who want Cowork to orchestrate local codex/claude workflows with conversational pre-launch confirmations.',
    tool_impact: [
      'start_codex_cli_run',
      'start_claude_cli_run',
      'external_cli_get_progress',
      'external_cli_respond',
      'external_cli_cancel_run',
    ],
    security_notes: 'Disable when you do not want agents invoking external local CLIs.',
    requires_new_session: false,
  },
  {
    id: 'integration.externalCli.allowBypassPermissions',
    title: 'External CLI Bypass Permissions',
    description: 'Allows bypass mode to be selected for external CLI runs.',
    what_it_controls:
      'Permits `bypassPermission=true` for provider start tools. The agent should still ask for conversational confirmation each launch.',
    when_to_use:
      'Enable only in trusted environments where bypass may be needed after user confirmation.',
    tool_impact: ['start_codex_cli_run', 'start_claude_cli_run'],
    security_notes: 'Bypass mode can execute high-risk actions without HITL checks. Keep disabled by default.',
    requires_new_session: false,
  },
  {
    id: 'integration.computerUseModel',
    title: 'Computer Use Model',
    description: 'Model ID used by computer_use browser automation tooling.',
    what_it_controls: 'Changes backend model used for autonomous browser tasks.',
    when_to_use: 'Adjust from Runtime tab when evaluating capability/performance changes.',
    tool_impact: ['computer_use'],
    security_notes: 'Model behavior influences automation reliability.',
    requires_new_session: false,
  },
  {
    id: 'integration.deepResearchModel',
    title: 'Deep Research Model',
    description: 'Model ID used for deep_research workflows.',
    what_it_controls: 'Defines the long-running research engine model.',
    when_to_use: 'Adjust from Runtime tab when testing output quality or cost differences.',
    tool_impact: ['deep_research'],
    security_notes: 'Long-running jobs may consume more quota.',
    requires_new_session: false,
  },
  {
    id: 'integration.sharedSessionWorkingDirectory',
    title: 'Shared Integration Working Directory',
    description: 'Default working directory for integration-triggered shared sessions.',
    what_it_controls:
      'Sets filesystem root context for messaging shared sessions (WhatsApp, Slack, Telegram, Discord, iMessage, Teams).',
    when_to_use: 'Set to your primary workspace for predictable file tool behavior.',
    tool_impact: [
      'read_any_file',
      'file tools',
      'shell tools in shared sessions',
      'integration-triggered workflow runs',
    ],
    security_notes: 'Choose directories with only data you want integrations to access.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.connection',
    title: 'WhatsApp Connection',
    description: 'Connects a WhatsApp identity to receive/send integration messages.',
    what_it_controls: 'Enables WhatsApp-based shared session messaging and notifications.',
    when_to_use: 'Enable for chat-based remote control or notifications through WhatsApp.',
    tool_impact: ['send_notification_whatsapp', 'shared-session ingress'],
    security_notes: 'Use a dedicated account/number for operational safety.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.allowlist',
    title: 'WhatsApp Sender Allowlist',
    description: 'Restricts which phone numbers can trigger the agent.',
    what_it_controls: 'Blocks unauthorized senders before they reach agent execution.',
    when_to_use: 'Always keep allowlist tight in production-like setups.',
    tool_impact: ['shared-session ingress policy'],
    security_notes: 'Primary safety boundary for WhatsApp ingress.',
    requires_new_session: false,
  },
  {
    id: 'whatsapp.denialMessage',
    title: 'WhatsApp Denial Message',
    description: 'Reply sent to unauthorized senders.',
    what_it_controls: 'User-facing rejection text for blocked numbers.',
    when_to_use: 'Customize messaging tone while keeping security intent clear.',
    tool_impact: ['shared-session ingress policy'],
    security_notes: 'Avoid revealing internal system details in denial responses.',
    requires_new_session: false,
  },
  {
    id: 'slack.connection',
    title: 'Slack Connection',
    description: 'Connects Slack bot tokens for Slack-based messaging integration.',
    what_it_controls: 'Enables Slack messaging ingress and notification tools.',
    when_to_use: 'Enable when teams coordinate tasks from Slack.',
    tool_impact: ['send_notification_slack', 'shared-session ingress'],
    security_notes: 'Use scoped tokens and minimal channel access.',
    requires_new_session: false,
  },
  {
    id: 'slack.botToken',
    title: 'Slack Bot Token',
    description: 'Bot OAuth token used for Slack API calls.',
    what_it_controls: 'Authorizes bot messaging and channel operations.',
    when_to_use: 'Required for Slack connector authentication.',
    tool_impact: ['send_notification_slack', 'slack inbound/outbound'],
    security_notes: 'Treat as secret; rotate immediately if exposed.',
    requires_new_session: false,
  },
  {
    id: 'slack.appToken',
    title: 'Slack App Token',
    description: 'App-level token for socket/event connectivity.',
    what_it_controls: 'Required for real-time connection lifecycle in Slack integration.',
    when_to_use: 'Set alongside bot token for stable Slack connectivity.',
    tool_impact: ['slack inbound/outbound'],
    security_notes: 'Keep token private and scope to required capabilities.',
    requires_new_session: false,
  },
  {
    id: 'telegram.connection',
    title: 'Telegram Connection',
    description: 'Connects Telegram bot for messaging integration.',
    what_it_controls: 'Enables Telegram message ingress and outbound notifications.',
    when_to_use: 'Enable when Telegram is used as operator/control channel.',
    tool_impact: ['send_notification_telegram', 'shared-session ingress'],
    security_notes: 'Use dedicated bot token and restrict bot visibility where possible.',
    requires_new_session: false,
  },
  {
    id: 'telegram.botToken',
    title: 'Telegram Bot Token',
    description: 'Bot token generated from BotFather for Telegram API access.',
    what_it_controls: 'Authenticates Telegram bot connectivity and messaging.',
    when_to_use: 'Required for Telegram connector setup.',
    tool_impact: ['send_notification_telegram', 'telegram inbound/outbound'],
    security_notes: 'Leakage gives bot-level control; rotate if compromised.',
    requires_new_session: false,
  },
  {
    id: 'discord.connection',
    title: 'Discord Connection',
    description: 'Connects a Discord bot for messaging ingress and notifications.',
    what_it_controls: 'Enables Discord shared-session ingress and send_notification_discord tool registration.',
    when_to_use: 'Enable when Discord is part of your operator workflow.',
    tool_impact: ['send_notification_discord', 'shared-session ingress'],
    security_notes: 'Restrict bot scope by guild/channel where possible.',
    requires_new_session: false,
  },
  {
    id: 'discord.botToken',
    title: 'Discord Bot Token',
    description: 'Bot token from Discord Developer Portal.',
    what_it_controls: 'Authenticates Discord gateway and REST operations for message ingress/egress.',
    when_to_use: 'Required for Discord integration setup.',
    tool_impact: ['send_notification_discord', 'discord inbound/outbound'],
    security_notes: 'Keep token secret and rotate immediately if exposed.',
    requires_new_session: false,
  },
  {
    id: 'discord.allowedGuildIds',
    title: 'Discord Allowed Guild IDs',
    description: 'Optional allowlist of Discord server IDs.',
    what_it_controls: 'Restricts inbound processing to specific guilds.',
    when_to_use: 'Use to narrow Discord ingress blast radius.',
    tool_impact: ['discord inbound filtering'],
    security_notes: 'Prefer explicit allowlists for production use.',
    requires_new_session: false,
  },
  {
    id: 'discord.allowedChannelIds',
    title: 'Discord Allowed Channel IDs',
    description: 'Optional allowlist of Discord channel IDs.',
    what_it_controls: 'Restricts inbound processing to specific channels.',
    when_to_use: 'Use to isolate bot usage to approved channels.',
    tool_impact: ['discord inbound filtering'],
    security_notes: 'Tight channel scoping reduces accidental ingress.',
    requires_new_session: false,
  },
  {
    id: 'discord.allowDirectMessages',
    title: 'Discord Direct Messages',
    description: 'Controls whether Discord direct messages are accepted.',
    what_it_controls: 'Enables/disables DM ingress for Discord.',
    when_to_use: 'Disable for server-only workflows.',
    tool_impact: ['discord inbound filtering'],
    security_notes: 'Disabling DMs can reduce unsolicited ingress.',
    requires_new_session: false,
  },
  {
    id: 'imessage.connection',
    title: 'iMessage Connection',
    description: 'Connects iMessage through a BlueBubbles bridge.',
    what_it_controls: 'Enables iMessage shared-session ingress and send_notification_imessage tool registration.',
    when_to_use: 'Enable on macOS when BlueBubbles bridge is configured.',
    tool_impact: ['send_notification_imessage', 'shared-session ingress'],
    security_notes: 'macOS-only; protect BlueBubbles endpoint and token.',
    requires_new_session: false,
  },
  {
    id: 'imessage.serverUrl',
    title: 'BlueBubbles Server URL',
    description: 'Endpoint of your BlueBubbles server.',
    what_it_controls: 'Determines where iMessage API/stream requests are sent.',
    when_to_use: 'Set to your reachable BlueBubbles host URL.',
    tool_impact: ['imessage inbound/outbound'],
    security_notes: 'Use trusted local/private endpoints whenever possible.',
    requires_new_session: false,
  },
  {
    id: 'imessage.accessToken',
    title: 'BlueBubbles Access Token',
    description: 'API token for BlueBubbles authentication.',
    what_it_controls: 'Authorizes iMessage bridge requests.',
    when_to_use: 'Required for iMessage bridge connection.',
    tool_impact: ['imessage inbound/outbound', 'send_notification_imessage'],
    security_notes: 'Treat as high-sensitivity credential.',
    requires_new_session: false,
  },
  {
    id: 'imessage.defaultChatGuid',
    title: 'Default iMessage Chat GUID',
    description: 'Optional default chat target for outbound notifications.',
    what_it_controls: 'Defines fallback destination when no active iMessage thread is known.',
    when_to_use: 'Set when you want deterministic outbound destination.',
    tool_impact: ['send_notification_imessage'],
    security_notes: 'Ensure GUID points to intended recipient/thread.',
    requires_new_session: false,
  },
  {
    id: 'imessage.allowHandles',
    title: 'Allowed iMessage Handles',
    description: 'Optional allowlist of sender handles/addresses.',
    what_it_controls: 'Restricts inbound iMessage processing to known handles.',
    when_to_use: 'Use to lock inbound scope to trusted senders.',
    tool_impact: ['imessage inbound filtering'],
    security_notes: 'Recommended for private/production usage.',
    requires_new_session: false,
  },
  {
    id: 'imessage.pollIntervalSeconds',
    title: 'iMessage Poll Interval',
    description: 'Fallback polling interval when stream events are not available.',
    what_it_controls: 'How frequently bridge polling checks for new messages.',
    when_to_use: 'Increase for lower load, decrease for lower latency.',
    tool_impact: ['imessage ingress latency'],
    security_notes: 'Excessively low intervals can increase bridge/API load.',
    requires_new_session: false,
  },
  {
    id: 'teams.connection',
    title: 'Teams Connection',
    description: 'Connects Microsoft Teams through Azure Graph app credentials.',
    what_it_controls: 'Enables Teams shared-session ingress and send_notification_teams tool registration.',
    when_to_use: 'Enable for Teams-based operator workflows.',
    tool_impact: ['send_notification_teams', 'shared-session ingress'],
    security_notes: 'Prefer least-privilege app permissions and secured secrets.',
    requires_new_session: false,
  },
  {
    id: 'teams.tenantId',
    title: 'Teams Tenant ID',
    description: 'Azure AD tenant identifier used for token issuance.',
    what_it_controls: 'Selects the Microsoft tenant for Graph authentication.',
    when_to_use: 'Required for Teams app auth setup.',
    tool_impact: ['teams inbound/outbound'],
    security_notes: 'Not secret, but should match intended tenant.',
    requires_new_session: false,
  },
  {
    id: 'teams.clientId',
    title: 'Teams Client ID',
    description: 'Azure app (client) ID.',
    what_it_controls: 'Identifies the app used to access Graph APIs.',
    when_to_use: 'Required for Teams app auth setup.',
    tool_impact: ['teams inbound/outbound'],
    security_notes: 'Pair with tenant/client secret securely.',
    requires_new_session: false,
  },
  {
    id: 'teams.clientSecret',
    title: 'Teams Client Secret',
    description: 'Azure app client secret for Graph client-credential flow.',
    what_it_controls: 'Authenticates Teams integration app to Graph.',
    when_to_use: 'Required for Teams app auth setup.',
    tool_impact: ['teams inbound/outbound', 'send_notification_teams'],
    security_notes: 'High-sensitivity secret; rotate regularly.',
    requires_new_session: false,
  },
  {
    id: 'teams.teamId',
    title: 'Teams Team ID',
    description: 'Target Microsoft Team identifier.',
    what_it_controls: 'Selects which Team channel scope is monitored/sent to.',
    when_to_use: 'Required for Teams routing setup.',
    tool_impact: ['teams inbound/outbound'],
    security_notes: 'Limit to intended Team only.',
    requires_new_session: false,
  },
  {
    id: 'teams.channelId',
    title: 'Teams Channel ID',
    description: 'Target Teams channel identifier.',
    what_it_controls: 'Selects specific channel for ingress and outbound notifications.',
    when_to_use: 'Required for Teams routing setup.',
    tool_impact: ['teams inbound/outbound', 'send_notification_teams'],
    security_notes: 'Restrict to approved operational channels.',
    requires_new_session: false,
  },
  {
    id: 'teams.pollIntervalSeconds',
    title: 'Teams Poll Interval',
    description: 'Polling interval for checking channel messages.',
    what_it_controls: 'Frequency of inbound Teams message checks.',
    when_to_use: 'Tune for latency vs API usage tradeoff.',
    tool_impact: ['teams ingress latency'],
    security_notes: 'Lower intervals increase Graph API request volume.',
    requires_new_session: false,
  },
  {
    id: 'remote.tunnelMode',
    title: 'Remote Tunnel Mode',
    description: 'Selects how remote phone traffic reaches the local desktop gateway.',
    what_it_controls: 'Switches remote networking path between Tailscale, Cloudflare Tunnel, or custom endpoint mode.',
    when_to_use: 'Choose based on your network/security model and whether you want managed setup from UI.',
    tool_impact: ['mobile gateway', 'pairing endpoint generation', 'remote websocket stream'],
    security_notes: 'Use managed secure tunnel modes for internet access; avoid exposing raw local ports.',
    requires_new_session: false,
  },
  {
    id: 'remote.tunnelLifecycle',
    title: 'Remote Tunnel Lifecycle',
    description: 'Install dependency, authenticate, and start/stop tunnel directly from Settings.',
    what_it_controls: 'Runs dependency checks/install/auth and managed tunnel runtime controls for remote access.',
    when_to_use: 'Use when enabling phone access without terminal setup steps.',
    tool_impact: ['remote endpoint reachability', 'mobile pairing readiness'],
    security_notes: 'Only start tunnels when needed and stop when idle for a smaller exposure window.',
    requires_new_session: false,
  },
  {
    id: 'remote.pairingQr',
    title: 'Remote Pairing QR',
    description: 'Generates short-lived QR payload for linking iOS/Android mobile app.',
    what_it_controls: 'Issues one-time pairing codes and device tokens scoped to remote API access.',
    when_to_use: 'Use whenever onboarding a new phone or re-linking after device reset/logout.',
    tool_impact: ['remote device registration', 'mobile auth token issuance'],
    security_notes: 'QR expires quickly and should only be scanned by the intended device owner.',
    requires_new_session: false,
  },
];

export const SETTINGS_HELP_BY_ID: Record<string, SettingHelpEntry> = SETTINGS_HELP_CONTENT.reduce(
  (acc, entry) => {
    acc[entry.id] = entry;
    return acc;
  },
  {} as Record<string, SettingHelpEntry>,
);

export function getSettingHelp(settingId: string): SettingHelpEntry | undefined {
  return SETTINGS_HELP_BY_ID[settingId];
}
